server:
  port: 9000

spring:
  application:
    name: spring-cloud-gateway
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.50:33066/medicalip_login
    password: medicalip808!
    username: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true

  jwt:
    secret: medicalip808

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true

  cloud:
    gateway:
      routes:
        - id: login-service
          uri: http://localhost:8081
          predicates:
            - Path=/login-service/**
          filters:
            - AuthFilter

        - id: first-service
          uri: http://localhost:8082
          predicates:
            - Path=/first-service/**
          filters:
            - AuthFilter
#  data:
#    redis:
#      port: 6379
#      host: 192.168.1.50
#      password: medicalip808!
#      lettuce:
#        pool:
#          max-active: 10
#          max-idle: 10
#          min-idle: 2
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka



