server:
  port: 9000

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login-service/**

        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka
